// <auto-generated />
using Drochclicker.Pages.Database_info;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drochclicker.Migrations
{
    [DbContext(typeof(DbContextInfo))]
    [Migration("20250805142503_Shop")]
    partial class Shop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrochClicker.Services.ShopInfo", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("DrochClicker.Services.UserInfo", b =>
                {
                    b.Property<string>("UserLogin")
                        .HasColumnType("text");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Rebirth")
                        .HasColumnType("integer");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer");

                    b.HasKey("UserLogin", "UpgradeId");

                    b.HasIndex("UpgradeId");

                    b.ToTable("UserUpgrades");
                });

            modelBuilder.Entity("Drochclicker.Pages.Database_info.UserContext", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Login");

                    b.ToTable("DataBase");
                });

            modelBuilder.Entity("DrochClicker.Services.UserInfo", b =>
                {
                    b.HasOne("DrochClicker.Services.ShopInfo", "Upgrade")
                        .WithMany()
                        .HasForeignKey("UpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drochclicker.Pages.Database_info.UserContext", "User")
                        .WithMany("UserUpgrades")
                        .HasForeignKey("UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upgrade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drochclicker.Pages.Database_info.UserContext", b =>
                {
                    b.Navigation("UserUpgrades");
                });
#pragma warning restore 612, 618
        }
    }
}
